// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"guoshao-fm-patch/internal/service/internal/dao/internal"
)

// dailyFeedItemRecordDao is the data access object for table daily_feed_item_record.
// You can define custom methods on it to extend its functionality as you wish.
type dailyFeedItemRecordDao struct {
	*internal.DailyFeedItemRecordDao
}

var (
	// DailyFeedItemRecord is globally public accessible object for table daily_feed_item_record operations.
	DailyFeedItemRecord = dailyFeedItemRecordDao{
		internal.NewDailyFeedItemRecordDao(),
	}
)

// Fill with you ideas below.
