// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"guoshao-fm-patch/internal/service/internal/dao/internal"
)

// feedItemMigrateDao is the data access object for table feed_item_migrate.
// You can define custom methods on it to extend its functionality as you wish.
type feedItemMigrateDao struct {
	*internal.FeedItemMigrateDao
}

var (
	// FeedItemMigrate is globally public accessible object for table feed_item_migrate operations.
	FeedItemMigrate = feedItemMigrateDao{
		internal.NewFeedItemMigrateDao(),
	}
)

// Fill with you ideas below.
