// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"guoshao-fm-patch/internal/service/internal/dao/internal"
)

// feedChannelMigrateDao is the data access object for table feed_channel_migrate.
// You can define custom methods on it to extend its functionality as you wish.
type feedChannelMigrateDao struct {
	*internal.FeedChannelMigrateDao
}

var (
	// FeedChannelMigrate is globally public accessible object for table feed_channel_migrate operations.
	FeedChannelMigrate = feedChannelMigrateDao{
		internal.NewFeedChannelMigrateDao(),
	}
)

// Fill with you ideas below.
