// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"guoshao-fm-patch/internal/model/entity"
	"guoshao-fm-patch/internal/service/internal/dao/internal"
)

// feedChannelMigrateDao is the data access object for table feed_channel_migrate.
// You can define custom methods on it to extend its functionality as you wish.
type feedChannelMigrateDao struct {
	*internal.FeedChannelMigrateDao
}

var (
	// FeedChannelMigrate is globally public accessible object for table feed_channel_migrate operations.
	FeedChannelMigrate = feedChannelMigrateDao{
		internal.NewFeedChannelMigrateDao(),
	}
)

// Fill with you ideas below.
func GetMigrateZHFeedChannelTotalCount(ctx context.Context) (count int, err error) {

	count, err = FeedChannelMigrate.Ctx(ctx).Where("language like 'zh%'").Count()

	return
}

func GetMigrateChannelList(ctx context.Context, offset, limit int) (entities []entity.FeedChannelMigrate, err error) {

	err = FeedChannelMigrate.Ctx(ctx).Offset(offset).Limit(limit).Scan(&entities)

	return
}

func GetMigrateZHFeedChannelList(ctx context.Context) (entities []entity.FeedChannel, err error) {

	err = FeedChannelMigrate.Ctx(ctx).Where("language like 'zh%'").Scan(&entities)

	return
}