// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"errors"
	"guoshao-fm-patch/internal/dto"
	"guoshao-fm-patch/internal/model/entity"
	"guoshao-fm-patch/internal/service/internal/dao/internal"

	"github.com/gogf/gf/v2/frame/g"
)

// feedItemDao is the data access object for table feed_item.
// You can define custom methods on it to extend its functionality as you wish.
type feedItemDao struct {
	*internal.FeedItemDao
}

var (
	// FeedItem is globally public accessible object for table feed_item operations.
	FeedItem = feedItemDao{
		internal.NewFeedItemDao(),
	}
)

// Fill with you ideas below.
func GetFeedItemsByChannelId(ctx context.Context, channelId string) (itemList []entity.FeedItem, err error) {

	err = FeedItem.Ctx(ctx).Where("channel_id=?", channelId).Scan(&itemList)
	if err != nil {
		return
	}

	if len(itemList) == 0 {
		return itemList, errors.New("The feed item is empty.")
	}

	return
}

func GetFeedItemCountByChannelId(ctx context.Context, channelId string) (count int, err error) {

	count, err = FeedItem.Ctx(ctx).Where("channel_id=?", channelId).Count()

	return
}

func GetFeedItemListByPubDate(ctx context.Context, startDate, endDate string) (entities []dto.FeedItem) {

	g.Model("feed_item fi").
		InnerJoin("feed_channel fc", "fc.id=fi.channel_id").
		Fields("fi.title, fi.link, fi.pub_date, fi.author, fi.input_date, fi.image_url, fi.enclosure_url, fi.enclosure_type, fi.enclosure_length, fi.duration, fi.episode, fi.explicit, fi.season, fi.episodeType, fi.description, fc.image_url as channel_image_url, fc.feed_link, fc.title as channel_title, fc.author as channelAuthor").
		Where("fi.pub_date>=?", startDate).
		Where("fi.pub_date<?", endDate).
		Scan(&entities)

	return
}
