// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"guoshao-fm-patch/internal/service/internal/dao/internal"
)

// userSubKeywordDao is the data access object for table user_sub_keyword.
// You can define custom methods on it to extend its functionality as you wish.
type userSubKeywordDao struct {
	*internal.UserSubKeywordDao
}

var (
	// UserSubKeyword is globally public accessible object for table user_sub_keyword operations.
	UserSubKeyword = userSubKeywordDao{
		internal.NewUserSubKeywordDao(),
	}
)

// Fill with you ideas below.
