// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-08-12 16:28:28
// =================================================================================

package entity

// FeedChannelMigrate is the golang structure for table feed_channel_migrate.
type FeedChannelMigrate struct {
	Id          string `json:"id"          ` //
	Ido         string `json:"ido"         ` //
	Title       string `json:"title"       ` //
	ChannelDesc string `json:"channelDesc" ` //
	ImageUrl    string `json:"imageUrl"    ` //
	Link        string `json:"link"        ` //
	FeedLink    string `json:"feedLink"    ` //
	Copyright   string `json:"copyright"   ` //
	Language    string `json:"language"    ` //
	Author      string `json:"author"      ` //
	OwnerName   string `json:"ownerName"   ` //
	OwnerEmail  string `json:"ownerEmail"  ` //
	FeedType    string `json:"feedType"    ` //
	Categories  string `json:"categories"  ` //
}
