// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-06-11 18:16:17
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserListenLater is the golang structure for table user_listen_later.
type UserListenLater struct {
	Id        string      `json:"id"        ` //
	UserId    string      `json:"userId"    ` //
	ItemId    string      `json:"itemId"    ` //
	ChannelId string      `json:"channelId" ` //
	RegDate   *gtime.Time `json:"regDate"   ` //
}
